#!/bin/bash
git pull origin master
git pull --no-edit upstream master
git push origin master
cp ~/GitHub/COVID-19/csse_covid_19_data/csse_covid_19_time_series/*  ~/GitHub/R-COVID-19/data
curl https://covidtracking.com/api/v1/states/daily.csv > ~/GitHub/R-COVID-19/data/covid-tracking-state.csv 
curl https://data.cdc.gov/api/views/hk9y-quqm/rows.csv > ~/GitHub/R-COVID-19/data/CDC.csv
